name: 'Build | Node.js'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    working-directory: bedrock-image-generator-frontend

jobs:

  e2e:
    name: Run e2e
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      - name: Start server in the background
        run: npm start &

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: bedrock-image-generator-frontend/cypress
          browser: chrome

  build:
    name: Build project
    runs-on: ubuntu-24.04
    needs: [ e2e ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      - name: Build
        run: npm run build

